//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTienda.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.LineaCompra = new HashSet<LineaCompra>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_Comprador { get; set; }
        public Nullable<int> Id_Vendedor { get; set; }
        public System.DateTime Fecha { get; set; }
        public int FormaPago { get; set; }
        public decimal Descuento { get; set; }
    
        public virtual Persona Persona { get; set; }
        public virtual Empleado Empleado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LineaCompra> LineaCompra { get; set; }
    }
}
